### ISSUE TITLE
vaults and pools abis

### ISSUE THREAD

**Issue by adrienlacombe-ledger** [bogdoslavik/harvest-ledger-plugin#1]
Hey hi, I would need one json per address here please https://github.com/bogdoslavik/harvest-ledger-plugin/tree/master/tests/harvest/abis thank you vm!

**Comment by bogdoslavik** [comment]
Hi Adrien! There is 2 contract types with almost compatible abi (with selectors we use) - Vault ("Vault") and Pool ("NoMintRewardPool"). 

You can fetch current addresses (for all supported networks) from the api:
https://api-ui.harvest.finance/vaults?key=41e90ced-d559-4433-b390-af424fdc76d6
https://api-ui.harvest.finance/pools?key=41e90ced-d559-4433-b390-af424fdc76d6

I have created update script 
tests/harvest/update-contracts-info-b2c.mjs

What I missed out? 

Do you need just copies of same json files with different names? Why we should duplicate abi code?

If we have to duplicate files, what name format I have to use?

**Comment by adrienlacombe-ledger** [comment]
fixed
