### ISSUE TITLE
handle scenario in which contract is not found

### ISSUE THREAD

**Issue by adrienlacombe-ledger** [bogdoslavik/harvest-ledger-plugin#5]
If a contract is not found, tickers are not displayed. This is misleading, and could trick a user into performing an operation on assets not displayed by the device. Plug-in must fail and trigger an error if the contract address is not known.

**Comment by bogdoslavik** [comment]
I fixed handle_finalize for not found contract info now returns 
ETH_PLUGIN_RESULT_UNAVAILABLE
or it should return 
ETH_PLUGIN_RESULT_ERROR / ETH_PLUGIN_RESULT_UNSUCCESSFUL ?
